version: '3.8'
services:
  service1:
    build: ./service_1
    ports:
      - "8001:8000"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  service2:
    build: ./service_2
    ports:
      - "8002:8000"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  backend:
    driver: bridge